# Generated by Django 3.1.2 on 2020-11-02 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverableInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('deliverable_name', models.CharField(max_length=100)),
                ('git_url', models.URLField()),
                ('category', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=50)),
                ('own_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('non_display', models.CharField(blank=True, max_length=6, null=True)),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_dt', models.DateTimeField(blank=True, null=True)),
                ('good_num', models.IntegerField(default=0)),
                ('good', models.TextField(blank=True, null=True)),
                ('comment_num', models.IntegerField(default=0)),
            ],
        ),
    ]
