# Generated by Django 3.1.2 on 2020-10-20 01:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverableInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('deliverable_name', models.CharField(max_length=100)),
                ('git_url', models.URLField()),
                ('category', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=50)),
                ('own_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_dt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PablicComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('deliverable_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.deliverableinfo')),
            ],
        ),
    ]
