# Generated by Django 3.1.1 on 2020-10-14 02:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverableInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('git_url', models.URLField()),
                ('category', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=50)),
                ('option', models.CharField(blank=True, max_length=100, null=True)),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_dt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
