# Generated by Django 3.1.2 on 2020-11-02 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PablicComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_user_id', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=140)),
                ('deliverable_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.deliverableinfo')),
            ],
        ),
    ]
