# Generated by Django 3.1.1 on 2020-10-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverableinfo',
            name='user_id',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverableinfo',
            name='user_name',
            field=models.CharField(default='sample', max_length=100),
            preserve_default=False,
        ),
    ]
