# Generated by Django 3.1.2 on 2020-10-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pabliccomment',
            name='post_user_id',
            field=models.CharField(default='naoki', max_length=100),
            preserve_default=False,
        ),
    ]
