# Generated by Django 3.1.1 on 2020-10-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201015_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverableinfo',
            old_name='name',
            new_name='deliverable_name',
        ),
        migrations.RenameField(
            model_name='deliverableinfo',
            old_name='option',
            new_name='own_comment',
        ),
        migrations.RemoveField(
            model_name='deliverableinfo',
            name='user_name',
        ),
    ]
