# Generated by Django 3.1.2 on 2020-10-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_deliverableinfo_non_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverableinfo',
            name='non_display',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
    ]
