# Generated by Django 3.1.2 on 2020-10-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201023_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverableinfo',
            name='good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverableinfo',
            name='non_display',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
