# Generated by Django 3.1.2 on 2020-10-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201023_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pabliccomment',
            name='comment',
            field=models.TextField(max_length=140),
        ),
    ]
